
services:
# noop change to trigger deploy workflow
  {{ cookiecutter.service_name }}:
    image: your-image:tag
    container_name: ${SERVICE_NAME}
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - services_lan
    volumes:
      - /data/${SERVICE_NAME}:/config
    restart: unless-stopped
    labels:
      - homepage.enable=true
      - homepage.name={{ cookiecutter.service_name | title }}
      - homepage.group={{ cookiecutter.service_group }}
      - homepage.icon={{ cookiecutter.service_icon }}
      - homepage.href=https://${SERVICE_NAME}.${BASE_DOMAIN:-{{ cookiecutter.base_domain }}}

networks:
  services_lan:
    name: service_internal_lan
    external: true
